/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_doan2;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lyhoa
 */
public class Bien_Ban_Kiem_Ke extends javax.swing.JFrame {

    /**
     * Creates new form Bien_Ban_Kiem_Ke
     */
    public Bien_Ban_Kiem_Ke(String makiemke) {
        initComponents();
        loaddata(makiemke);
        loadtable(makiemke);
    }

    public void loaddata(String makiemke){
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            Statement dd = conn.createStatement();
            ResultSet  kq = dd.executeQuery("select tengiaovien,chucvu,ngaykiemke from kiemke where tinhtrangkiemduyet like 0 and makiemke like '"+makiemke+"'");
                 while(kq.next()){
                     lb_tengiaovien.setText(kq.getString(1));
                     lb_chucvu.setText(kq.getString(2));
                    String str[] = kq.getString(3).toString().split("-");
                    String ngaykiemke=str[2]+"-"+str[1]+"-"+str[0];
                     
                     lb_thoigiankk.setText(ngaykiemke);
                     lb_thoigiankk2.setText(ngaykiemke);
                 }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    public String tenphong(String maphong){
        String tenphong="";
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            Statement dd = conn.createStatement();
            ResultSet  kq = dd.executeQuery("select tenphong from phonghoc where maphong like '"+maphong+"'");
                 while(kq.next()){
                     tenphong=kq.getString(1);  
                 }
        }catch(Exception ex){
            maphong="";  
            System.out.println(ex);
        }
        return tenphong;
    }
    public String maphong(String makiemke){
        String maphong="";
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            Statement dd = conn.createStatement();
            ResultSet  kq = dd.executeQuery("select maphong from kiemke where tinhtrangkiemduyet = 0 and makiemke like '"+makiemke+"'");
                 while(kq.next()){
                     maphong=kq.getString(1); 
                     maphong = tenphong(maphong);
                 }
        }catch(Exception ex){
            maphong="";  
            System.out.println(ex);
        }
        return maphong;
    }
    public String tinhtrangphong(String makiemke){
         String tinhtrangphong="";
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            Statement dd = conn.createStatement();
            ResultSet  kq = dd.executeQuery("select tinhtrangphong from kiemke where tinhtrangkiemduyet = 0 and makiemke like '"+makiemke+"'");
                 while(kq.next()){
                     tinhtrangphong=kq.getString(1); 
                     
                 }
        }catch(Exception ex){
            tinhtrangphong="";  
            System.out.println(ex);
        }
        return tinhtrangphong;
    }
    public void loadtable(String makiemke){
        DefaultTableModel tbn = (DefaultTableModel)tb_kk.getModel();
        try{
            
            Connect a = new Connect();
            Connection conn = a.getConnection();
            Statement dd = conn.createStatement();
            ResultSet  kq = dd.executeQuery("select tencsvc,tinhtrangcsvc,soluong,macsvc from kiemke_csvcphong where makiemke like '"+makiemke+"'");
                 while(kq.next()){
                     String tencsvc=kq.getString(1);
                     String tinhtrangcsvc=kq.getString(2);
                     String soluong=kq.getString(3);
                     String macsvc=kq.getString(4);
                    tbn.addRow(new Object[]{tencsvc,macsvc,soluong,tinhtrangcsvc,maphong(makiemke),tinhtrangphong(makiemke)});
                 }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    private Bien_Ban_Kiem_Ke() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_thoigiankk = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_tengiaovien = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_chucvu = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_kk = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lb_thoigiankk2 = new javax.swing.JLabel();
        btn_in = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Phần mềm quản lý cơ sở vật chất");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Trường THPT ABC");

        jLabel2.setText("Bộ Phận Quản Lý CSVC");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("BIÊN BẢN KIỂM KÊ CƠ SỞ VẬT CHẤT CỐ ĐỊNH");

        jLabel3.setText("Thời gian kiểm kê:");

        lb_thoigiankk.setText("mm/dd/yyyy");

        jLabel5.setText("Đại diện ban kiểm kê:");

        lb_tengiaovien.setText("họ tên");

        jLabel8.setText("Chức vụ:");

        lb_chucvu.setText("họ tên");

        jLabel10.setText("Kết quả sau khi kiểm kê như sau:");

        tb_kk.setBackground(java.awt.Color.white);
        tb_kk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên csvc", "Mã csvc", "SL trước KK", "Tình trạng csvc", "Phòng sử dụng", "Tình trạng phòng", "SL sau KK", "Chênh lệch SL", "Ghi chú"
            }
        ));
        jScrollPane1.setViewportView(tb_kk);

        jLabel11.setText("Hiệu trưởng");

        jLabel12.setText("(Ký, ghi rõ họ tên, đóng dấu)");

        jLabel13.setText("Ghi chú thêm ý kiến (Nếu có):");

        jLabel14.setText("...............................................");

        jLabel15.setText("Đại diện ban Quản lý");

        jLabel16.setText("(Ký, ghi rõ họ tên, đóng dấu)");

        jLabel17.setText("Đại diện ban Kiểm Kê");

        jLabel18.setText("(Ký, ghi rõ họ tên, đóng dấu)");

        lb_thoigiankk2.setText("dd/mm/yyyy");

        btn_in.setBackground(java.awt.Color.lightGray);
        btn_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_doan2/image/icons8-print-24.png"))); // NOI18N
        btn_in.setText("IN");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_doan2/image/icons8-go-back-24.png"))); // NOI18N
        jLabel19.setText("Trở về");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(191, 191, 191)
                                        .addComponent(jLabel14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_in, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel11))))
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_thoigiankk2)
                                .addGap(51, 51, 51)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_chucvu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_thoigiankk))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_tengiaovien))
                    .addComponent(jLabel6))
                .addGap(258, 258, 258))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_in))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lb_thoigiankk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lb_tengiaovien))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lb_chucvu))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_thoigiankk2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel16))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel19)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        Bien_Ban_Kiem_Ke.this.setVisible(false);
            new Xuat_Bien_Ban_KK().setVisible(true);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, "Thoát phần mềm?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
               System.exit(0);
            }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bien_Ban_Kiem_Ke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bien_Ban_Kiem_Ke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bien_Ban_Kiem_Ke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bien_Ban_Kiem_Ke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bien_Ban_Kiem_Ke().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_chucvu;
    private javax.swing.JLabel lb_tengiaovien;
    private javax.swing.JLabel lb_thoigiankk;
    private javax.swing.JLabel lb_thoigiankk2;
    private javax.swing.JTable tb_kk;
    // End of variables declaration//GEN-END:variables
}
