/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_doan2;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lyhoa
 */
public class Bien_Ban_Bao_Tri extends javax.swing.JFrame {

    Connect a = new Connect();
    Connection conn = a.getConnection();
    public Bien_Ban_Bao_Tri(String mavanban) {
        initComponents();
        loadcsvcbaotri(mavanban);
        loadtable(mavanban);
    }

    private Bien_Ban_Bao_Tri() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    public void loadcsvcbaotri(String mavanban){
         try{
            
            if (conn!=null){
                Statement dd = conn.createStatement();            
                 ResultSet  kq = dd.executeQuery("select  loaivanban,mavanban,idgiaovien,ngaybaotri,bensuachua,nguoidaidien,sdt,diachi,ngayhoanthanh from xuatvanban where mavanban like '"+mavanban+"' ");
                 while(kq.next()){
                    String ngaybaotri=kq.getString(4);
                    String bensuachua=kq.getString(5);
                    String nguoidaidien=kq.getString(6);
                    String sdt=kq.getString(7);
                    String diachi=kq.getString(8);
                    String ngayhoanthanh=kq.getString(9);
                    String idgiaovien=kq.getString(3);
                    Statement db = conn.createStatement();
                    ResultSet  gv = db.executeQuery("select tengiaovien,chucvu from taikhoan where idgiaovien like '"+idgiaovien+"'");
                    while(gv.next()){
                        String nguoidaidiena = gv.getString(1);
                        String chucvua = gv.getString(2);
                    
                    String str[] = ngaybaotri.toString().split("-");
                    String ngaybaotri1=str[2]+"-"+str[1]+"-"+str[0];   
                    String str1[] = ngayhoanthanh.toString().split("-");
                    String ngayhoanthanh1=str1[2]+"-"+str1[1]+"-"+str1[0];
                        
                    lb_ngay.setText(ngaybaotri1);
                    lb_mabienban.setText(mavanban);
                    lb_nguoidaidiena.setText(nguoidaidiena);
                    lb_chucvua.setText(chucvua);
                    lb_nguoidaidienb.setText(nguoidaidien);
                    lb_donvib.setText(bensuachua);
                    lb_diachib.setText(diachi);
                    lb_dienthoaib.setText(sdt);
                    lb_ngaygiao.setText(ngaybaotri1);
                    lb_ngayhoanthanh.setText(ngayhoanthanh1);
                    
                    
                   
                    
                    }  
                }
            }
                      
        }catch(Exception ex){
            System.out.print(ex.toString());
        }
    }
    public void loadtable(String mavanban){
        DefaultTableModel model = (DefaultTableModel)tb_cosovatchat.getModel();
    try{
            
            Statement dc = conn.createStatement();
            ResultSet  ad = dc.executeQuery("select tencsvc,cosovatchat.macsvc,soluong,cosovatchat.mota from cosovatchat,xuatvanban_csvc where mabaotri like mavanban and mavanban like '"+mavanban+"' and cosovatchat.macsvc like xuatvanban_csvc.macsvc");
            while(ad.next()){
                String tencsvc = ad.getString(1);
                String macsvc = ad.getString(2);
                int soluong = ad.getInt(3);
                String soluong2 = String.valueOf(soluong);
                String mota = ad.getString(4);
                model.addRow(new Object[]{tencsvc, macsvc,soluong2,mota});           
            }
            
        
    }catch(Exception ex){
        System.out.print(ex.toString());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ngay = new javax.swing.JLabel();
        mabienban = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btn_in = new javax.swing.JButton();
        label_trove = new javax.swing.JLabel();
        lb_nguoidaidiena = new javax.swing.JLabel();
        lb_chucvua = new javax.swing.JLabel();
        lb_nguoidaidienb = new javax.swing.JLabel();
        lb_donvib = new javax.swing.JLabel();
        lb_diachib = new javax.swing.JLabel();
        lb_dienthoaib = new javax.swing.JLabel();
        lb_ngaygiao = new javax.swing.JLabel();
        lb_ngayhoanthanh = new javax.swing.JLabel();
        lb_ngay = new javax.swing.JLabel();
        lb_mabienban = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_cosovatchat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Phần mềm quản lý cơ sở vật chất");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Trường THPT ABC");

        jLabel2.setText("Địa chỉ: Abc/Xyz/Uoi");

        jLabel3.setText("Điện thoại: 0123456789");

        ngay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ngay.setText("Ngày:");

        mabienban.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mabienban.setText("Mã biên bản:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("BIÊN BẢN SỬA CHỮA VÀ BẢO TRÌ CƠ SỞ VẬT CHẤT ");

        jLabel7.setText("Bên A gồm có đại diện:");

        jLabel8.setText("Của trường THPT: ABC");

        jLabel9.setText("Chức vụ hiện tại:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("-------------------------------------------------------------------------------------");

        jLabel11.setText("Bên B gồm có đại diện:");

        jLabel12.setText("Của đơn vị:");

        jLabel14.setText("Địa chỉ:");

        jLabel15.setText("Điện thoại:");

        jLabel16.setText("Với bên A là đơn vị được sửa chữa và bên B là đơn vị sửa chữa cơ sở vật chất cho bên A, cụ thể như sau:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("PHẦN I/ SỬA CHỮA - BẢO TRÌ:");

        jLabel18.setText(" bên A đã bàn giao cơ sở vật chất cần bảo trì - sửa chữa cho bên B");

        jLabel19.setText("bên B sẽ hoàn thành bảo trì - sửa chữa cơ sở vật chất và bàn giao lại cho bên A đúng thời hạn.");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setText("ĐẠI DIỆN BÊN A KÝ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("ĐẠI DIỆN BÊN B KÝ");

        jLabel22.setText("(Ký và ghi rõ họ tên)");

        jLabel23.setText("(Ký và ghi rõ họ tên)");

        btn_in.setBackground(java.awt.Color.lightGray);
        btn_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_doan2/image/icons8-print-24.png"))); // NOI18N
        btn_in.setText("IN");

        label_trove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_doan2/image/icons8-go-back-24.png"))); // NOI18N
        label_trove.setText("Trở về");
        label_trove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_troveMouseClicked(evt);
            }
        });

        lb_nguoidaidiena.setText("XXXXXXXXXXXXXXXXXX");

        lb_chucvua.setText("XXXXXXXXXXXXXXXXXX");

        lb_nguoidaidienb.setText("XXXXXXXXXXXXXXXXXX");

        lb_donvib.setText("XXXXXXXXXXXXXXXXXX");

        lb_diachib.setText("XXXXXXXXXXXXXXXXXX");

        lb_dienthoaib.setText("XXXXXXXXXXXXXXXXXX");

        lb_ngaygiao.setText("XXXXXXXXXXXXXXXXXX");

        lb_ngayhoanthanh.setText("XXXXXXXXXXXXXXXXXX");

        lb_ngay.setText("XXXXXXXXXXX");

        lb_mabienban.setText("XXXXXXXXXXX");

        tb_cosovatchat.setBackground(java.awt.Color.white);
        tb_cosovatchat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên csvc", "Mã csvc", "Số lượng", "Mô tả"
            }
        ));
        jScrollPane2.setViewportView(tb_cosovatchat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_trove)
                        .addGap(496, 496, 496)
                        .addComponent(btn_in, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb_ngaygiao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mabienban)
                                        .addComponent(ngay))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_ngay)
                                        .addComponent(lb_mabienban)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_ngayhoanthanh, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel22)))
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel23)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_nguoidaidiena)
                                    .addComponent(lb_chucvua)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(80, 80, 80)
                                .addComponent(lb_dienthoaib))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(77, 77, 77)
                                .addComponent(lb_donvib))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_nguoidaidienb))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(98, 98, 98)
                                .addComponent(lb_diachib))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ngay)
                    .addComponent(lb_ngay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mabienban)
                    .addComponent(lb_mabienban))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lb_nguoidaidiena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lb_chucvua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lb_nguoidaidienb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lb_donvib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_diachib)
                    .addComponent(jLabel14))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lb_dienthoaib))
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lb_ngaygiao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lb_ngayhoanthanh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_in)
                    .addComponent(label_trove))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_troveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_troveMouseClicked
        // TODO add your handling code here:
        Bien_Ban_Bao_Tri.this.setVisible(false);
        new Xuat_File().setVisible(true);
         
    }//GEN-LAST:event_label_troveMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Thoát phần mềm?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
               System.exit(0);
            }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bien_Ban_Bao_Tri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bien_Ban_Bao_Tri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bien_Ban_Bao_Tri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bien_Ban_Bao_Tri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bien_Ban_Bao_Tri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_trove;
    private javax.swing.JLabel lb_chucvua;
    private javax.swing.JLabel lb_diachib;
    private javax.swing.JLabel lb_dienthoaib;
    private javax.swing.JLabel lb_donvib;
    private javax.swing.JLabel lb_mabienban;
    private javax.swing.JLabel lb_ngay;
    private javax.swing.JLabel lb_ngaygiao;
    private javax.swing.JLabel lb_ngayhoanthanh;
    private javax.swing.JLabel lb_nguoidaidiena;
    private javax.swing.JLabel lb_nguoidaidienb;
    private javax.swing.JLabel mabienban;
    private javax.swing.JLabel ngay;
    private javax.swing.JTable tb_cosovatchat;
    // End of variables declaration//GEN-END:variables
}
