/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo_doan2;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author masqu
 */
public class Xuat_File extends javax.swing.JFrame {

    /**
     * Creates new form Xuat_File
     */
    public Xuat_File() {
        initComponents();
        loaddata();
    }

    public void loaddata(){
        DefaultTableModel model = (DefaultTableModel)table_danhsach.getModel();
         try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            if (conn!=null){
                Statement dd = conn.createStatement();            
                 ResultSet  kq = dd.executeQuery("select loaivanban,mavanban,ngaybaotri,idgiaovien from xuatvanban");
                 while(kq.next()){
                    String loaivanban = kq.getString(1);
                    String mavanbang=kq.getString(2);
                    String ngaybaotri=kq.getString(3);
                    String idgiaovien=kq.getString(4);
                    String str[] = ngaybaotri.toString().split("-");
                    String ngaybaotri1=str[2]+"-"+str[1]+"-"+str[0];
                    Statement da = conn.createStatement(); 
                    ResultSet  csvc = da.executeQuery("select tengiaovien from taikhoan where idgiaovien like '"+idgiaovien+"'");
                    while(csvc.next()){
                      String tengiaovien=csvc.getString(1);
                      model.addRow(new Object[]{loaivanban, mavanbang,ngaybaotri1,tengiaovien});
                 }
                   
                }
                
            }
                      
        }catch(Exception ex){
            System.out.print(ex.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_bienbanbaotricsvc = new javax.swing.JButton();
        btn_bienbankiemke = new javax.swing.JButton();
        btn_thongtin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_danhsach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("Kiểm kê csvc");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Phần mềm quản lý cơ sở vật chất");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_doan2/image/icons8-go-back-24.png"))); // NOI18N
        jLabel3.setText("Trở về");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_doan2/image/icons8-file-24.png"))); // NOI18N
        jLabel4.setText("XUẤT VĂN BẢN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn loại văn bản:"));

        btn_bienbanbaotricsvc.setBackground(java.awt.Color.lightGray);
        btn_bienbanbaotricsvc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_doan2/image/icons8-maintenance-24.png"))); // NOI18N
        btn_bienbanbaotricsvc.setText("Biên bản bảo trì csvc");
        btn_bienbanbaotricsvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bienbanbaotricsvcActionPerformed(evt);
            }
        });

        btn_bienbankiemke.setBackground(java.awt.Color.lightGray);
        btn_bienbankiemke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_doan2/image/icons8-warehouse-24.png"))); // NOI18N
        btn_bienbankiemke.setText("Biên bản kiểm kê csvc");
        btn_bienbankiemke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bienbankiemkeActionPerformed(evt);
            }
        });

        btn_thongtin.setBackground(java.awt.Color.lightGray);
        btn_thongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo_doan2/image/icons8-information-24.png"))); // NOI18N
        btn_thongtin.setText("Thông tin văn bản");
        btn_thongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongtinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_bienbankiemke, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(btn_bienbanbaotricsvc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_thongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_bienbanbaotricsvc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_bienbankiemke, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_thongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_danhsach.setBackground(java.awt.Color.white);
        table_danhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại văn bản", "Mã văn bản", "Ngày in", "Người lập "
            }
        ));
        jScrollPane1.setViewportView(table_danhsach);

        jLabel1.setText("Các văn bản đã in gần đây:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         Xuat_File.this.setVisible(false);
        new Menu_Quan_Ly().setVisible(true);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_bienbanbaotricsvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bienbanbaotricsvcActionPerformed
        Xuat_File.this.setVisible(false);
        new Xuat_Van_Ban_Bao_Tri().setVisible(true);
    }//GEN-LAST:event_btn_bienbanbaotricsvcActionPerformed

    private void btn_thongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongtinActionPerformed
        // TODO add your handling code here:
        
        try{
        int Row = table_danhsach.getSelectedRow();
        String mavanban = (String) table_danhsach.getValueAt(Row,1);
        String loaivanban = (String) table_danhsach.getValueAt(Row,0);
        if(loaivanban.equals("Biên bản bảo trì")){
        Xuat_File.this.setVisible(false);
        new Bien_Ban_Bao_Tri(mavanban.trim()).setVisible(true);
        }else if(loaivanban.equals("Biên bản kiểm kê")){
             Xuat_File.this.setVisible(false);
        new Bien_Ban_KK(mavanban.trim()).setVisible(true);
        }
        }catch(Exception ex){
           JOptionPane.showMessageDialog(null,"Vui lòng chọn 1 biên bản trong danh sách!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_thongtinActionPerformed

    private void btn_bienbankiemkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bienbankiemkeActionPerformed
        // TODO add your handling code here:
         Xuat_File.this.setVisible(false);
        new Xuat_Bien_Ban_KK().setVisible(true);
    }//GEN-LAST:event_btn_bienbankiemkeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
if (JOptionPane.showConfirmDialog(this, "Thoát phần mềm?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
               System.exit(0);
            }    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Xuat_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Xuat_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Xuat_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Xuat_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Xuat_File().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bienbanbaotricsvc;
    private javax.swing.JButton btn_bienbankiemke;
    private javax.swing.JButton btn_thongtin;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_danhsach;
    // End of variables declaration//GEN-END:variables
}
